(function(){const G=GB;let device=G.params.get('d')||'',garden=G.state.gardens[0]?.id||'',manual=false;
 const valid=id=>/^GB-\d{6}$/.test(id);
 if(!valid(device))device='';
 G.pages['add-device']=()=>{
 G.mount(`${G.header('迎接新夥伴','home.html','<span class="demo-badge">DEMO</span>')}${G.steps(1)}<div class="eyebrow caps">A NEW FRIEND IS ON THE WAY</div><h1>${device?'找到你的 GreenBuddy 了。':'先和小小感測器，\n打聲招呼。'.replace('\n','<br>')}</h1><p class="muted small mt8">${device?'選一個舒服的角落，讓它住下來。':'掃描裝置背面的綁定 QR，就能開始。'}</p><div class="device-art"><div class="device-light"></div>${G.icon('leaf')}<div class="qr">${G.icon('qr-code')}</div><p>GREENBUDDY SENSOR</p></div>${!device?`<button class="btn full" id="scan-device">${G.icon('scan')}掃描裝置上的 QR</button><div class="center mt8"><button class="text-link" id="manual-device">手動輸入裝置編號</button></div><p class="footnote">此步驟會模擬掃描，不需開啟相機。</p>`:`<div class="card"><div class="row">${G.icon('check-circle')}<div><h3>找到 ${G.esc(device)}</h3><p class="small muted">植物感測器 · 等待連線</p></div></div><label for="garden-select">放在哪個花圃？</label><select id="garden-select">${G.state.gardens.map(g=>`<option value="${g.id}" ${garden===g.id?'selected':''}>${G.esc(g.name)}</option>`).join('')}<option value="new">＋ 新增花圃</option></select></div><button class="btn full mt24" id="device-next">下一步，連上網路 ${G.icon('arrow-right')}</button><div class="center mt8"><button class="text-link" id="device-again">重新掃描</button></div>`}<div class="notice row">${G.icon('wifi-high')}<span>先準備好家中的 2.4GHz Wi-Fi，<br>我們會一步一步陪你完成。</span></div>`,false);
 document.getElementById('scan-device')?.addEventListener('click',async e=>{e.currentTarget.disabled=true;e.currentTarget.textContent='正在尋找裝置……';await new Promise(r=>setTimeout(r,600));let n=123;while(G.state.plants.some(p=>p.device==='GB-'+String(n).padStart(6,'0')))n++;device='GB-'+String(n).padStart(6,'0');G.refresh()});
 document.getElementById('manual-device')?.addEventListener('click',async()=>{const r=await G.dialog({title:'輸入裝置編號',input:'text',inputPlaceholder:'GB-000123',showCancelButton:true,confirmButtonText:'尋找裝置',inputValidator:value=>!valid(value.trim().toUpperCase())?'請輸入 GB- 加上 6 位數字。':G.state.plants.some(p=>p.device===value.trim().toUpperCase())?'這台設備已在你的花圃裡。':undefined});if(r.isConfirmed){device=r.value.trim().toUpperCase();G.refresh()}});
 document.getElementById('garden-select')?.addEventListener('change',async e=>{if(e.target.value==='new'){const g=await G.addGarden();if(g)garden=g.id;G.refresh()}else garden=e.target.value});
 document.getElementById('device-again')?.addEventListener('click',()=>{device='';G.refresh()});
 document.getElementById('device-next')?.addEventListener('click',()=>{if(!garden)return G.toast('先建立一個花圃吧。');if(G.state.plants.some(p=>p.device===device))return G.toast('這台設備已經綁定，請使用另一個編號。');G.state.draft={device,garden,connected:false};G.save();G.go('provision.html')});
 };
})();
