(function(){let garden='all',sensorFocus=null,overviewMetric='soil';GB.pages.home=()=>{if(GB.state.user.style==='game')return gameHome();if(GB.state.user.style==='simple')return dataHome();const G=GB,S=G.state,u=S.user;const h=new Date().getHours(),greet=h<12?'早安':h<18?'午安':'晚安';const tasks=S.tasks.filter(t=>t.status==='pending'&&t.due==='today'&&(garden==='all'||G.plant(t.plant)?.garden===garden));const plants=S.plants.filter(p=>garden==='all'||p.garden===garden).sort((a,b)=>(a.state==='happy')-(b.state==='happy'));const thirsty=plants.find(p=>p.state==='thirsty'),focus=thirsty||plants[0];const total=S.tasks.filter(t=>t.status==='pending'&&t.due==='today').length;
 const heroTitle=u.style==='simple'?`今天有 ${total} 項照護任務`:u.style==='game'?`今日花園任務<br>一起收集小成就。`:thirsty?`${G.esc(thirsty.name)}有點口渴，<br>在等你的一點關心。`:'有你在的日子，<br>每一片葉子都安心。';
 G.mount(`${G.header()}${G.modeTabs()}<div class="greeting"><div><div class="eyebrow">${new Intl.DateTimeFormat('zh-TW',{month:'long',day:'numeric',weekday:'long'}).format(new Date())}</div><h1>${greet}，${G.esc(u.name)} <span style="font-size:1.3rem">☀</span></h1></div><span class="user-avatar">${G.esc(u.name.slice(0,1))}</span></div>${S.plants.length?`<section class="hero-card home-hero"><div class="hero-orbit"></div><div class="hero-copy"><div class="caps">YOUR LITTLE GREEN WORLD</div><h2>${heroTitle}</h2><p>${u.style==='game'?`完成今日任務可得 ${S.tasks.filter(t=>t.status==='pending').reduce((n,t)=>n+t.xp,0)} XP`:`一起生活的第 ${u.daysTogether} 天`}</p>${G.nav(focus?'plant.html?id='+focus.id:'tasks.html',`去看看它 ${G.icon('arrow-up-right')}`,'hero-button')}</div>${renderPlant(focus?.species||'monstera',focus?.state||'happy',focus?.accessory)}</section>${G.xp()}<div class="section-head"><h2>我的綠色角落</h2><span class="small muted">${S.plants.length} 位夥伴</span></div><div class="chip-row" aria-label="篩選花圃">${[['all','全部'],...S.gardens.map(g=>[g.id,g.name])].map(([id,n])=>`<button class="chip ${garden===id?'active':''}" data-garden="${id}">${G.esc(n)}</button>`).join('')}</div><div class="section-head"><h2>今天的一點照顧 <span class="small muted">${tasks.length?`(${tasks.length})`:''}</span></h2>${G.nav('tasks.html',`看全部 ${tasks.length} 項 `+G.icon('caret-right'),'text-link')}</div><div class="stack">${tasks.length?tasks.slice(0,1).map(t=>{const p=G.plant(t.plant);return `<div class="task-mini">${renderPlant(p.species,p.state,p.accessory)}${G.nav('plant.html?id='+p.id,`<h3>${G.esc(p.name)}${{water_needed:'想喝水',temp_high:'想躲太陽',offline:'需要你看一下',dark:'想去窗邊',overwater:'需要休息'}[t.event]||'需要關心'}</h3><p>${{water_needed:'補一點水，就很幸福。',temp_high:'換到通風陰涼的地方。',offline:'檢查感測器與連線。'}[t.event]||G.esc(say(t.event,p))}</p>`,'grow')}<button class="check-btn" data-action="task-done" data-id="${t.id}" aria-label="完成${G.esc(p.name)}的任務">${G.icon('check')}</button></div>`}).join(''):`<div class="card row">${G.icon('check-circle')}<p class="small">今天都照顧好了，陪它們坐一會兒吧。</p></div>`}</div><div class="section-head"><h2>植物夥伴</h2><span class="small muted">${garden==='all'?'全部花圃':G.esc(G.garden(garden)?.name)}</span></div><div class="plant-grid">${plants.map(G.plantCard).join('')}</div>${!plants.length?'<p class="center muted mt24">這個角落還沒有植物。</p>':''}<p class="footnote">每一點小照顧，都會慢慢長成喜歡的樣子。</p>`:`<div class="empty-state">${renderPlant('monstera','sleeping')}<h2>這裡，留給你的第一盆綠。</h2><p>還沒有植物夥伴，<br>一起迎接第一盆吧。</p>${G.nav('add-device.html',G.icon('plus')+' 新增第一台設備','btn full')}</div>`}`);
 document.querySelectorAll('[data-garden]').forEach(b=>b.onclick=()=>{garden=b.dataset.garden;G.refresh()});
 }; 
 const filters=()=>`<div class="chip-row mode-garden-filter" aria-label="篩選花圃">${[['all','全部花圃'],...GB.state.gardens.map(g=>[g.id,g.name])].map(([id,name])=>`<button class="chip ${garden===id?'active':''}" data-garden="${id}">${GB.esc(name)}</button>`).join('')}</div>`;
 const bindFilters=()=>document.querySelectorAll('[data-garden]').forEach(b=>b.onclick=()=>{garden=b.dataset.garden;GB.refresh()});
 const scopedPlants=()=>GB.state.plants.filter(p=>garden==='all'||p.garden===garden);
 const scopedTasks=()=>GB.state.tasks.filter(t=>GB.plant(t.plant)&&(garden==='all'||GB.plant(t.plant).garden===garden));
 const empty=(mode)=>`<div class="mode-empty">${GB.icon(mode==='game'?'flag-checkered':'cpu')}<h2>${mode==='game'?'迎接第一位花園隊友':'加入第一台感測設備'}</h2><p>${mode==='game'?'綁定植物，開始累積你的照護成就。':'綁定設備後，就能在這裡查看環境指標與趨勢。'}</p>${GB.nav('add-device.html','新增設備 '+GB.icon('plus'),'btn full')}</div>`;
 const gameHome=()=>{
  const G=GB,plants=scopedPlants(),tasks=scopedTasks(),pending=tasks.filter(t=>t.status==='pending'&&t.due==='today');
  G.mount(`${G.workHeader()}${G.modeTabs()}<div class="mode-page-heading"><div><span class="mode-kicker">GARDEN QUEST</span><h1>任務營地</h1></div>${G.nav('closet.html',G.icon('treasure-chest')+' 衣櫥','text-link')}</div>${G.state.plants.length?`${G.questPlayer()}${filters()}${G.questProgress(tasks)}<div class="section-head"><h2>今日挑戰</h2>${G.nav('tasks.html','全部任務 '+G.icon('caret-right'),'text-link')}</div><div class="mission-list">${pending.length?pending.map(t=>G.taskCard(t,'game')).join(''):`<div class="quest-clear">${G.icon('check-circle')}<div><h3>這個花圃的任務已處理</h3><p>看看隊友，或去衣櫥領一份新造型。</p></div></div>`}</div>${G.rewardCard()}<div class="section-head"><h2>你的花園隊友</h2><span class="small muted">${plants.length} 位</span></div><div class="team-list">${plants.map(p=>G.nav('plant.html?id='+p.id,`${renderPlant(p.species,p.state,p.accessory)}<div><h3>${G.esc(p.name)}</h3><p>${tasks.filter(t=>t.plant===p.id&&t.status==='pending').length} 項待辦 · ${G.esc(p.speciesName)}</p></div>${G.icon('caret-right')}`,'team-row')).join('')||'<p class="small muted">這個花圃還沒有隊友。</p>'}</div>`:empty('game')}`);
  bindFilters();
 };
 const dataHome=()=>{
  const G=GB,plants=scopedPlants(),tasks=scopedTasks();
  const online=plants.filter(p=>p.online),abnormal=online.filter(p=>G.abnormalReadings(p).length),pending=tasks.filter(t=>t.status==='pending');
  const focus=plants.find(p=>p.id===sensorFocus)||abnormal[0]||online[0]||plants[0];
  if(focus)sensorFocus=focus.id;
  const rows=[...plants].sort((a,b)=>Number(!b.online||G.abnormalReadings(b).length>0)-Number(!a.online||G.abnormalReadings(a).length>0));
  G.mount(`${G.workHeader()}${G.modeTabs()}<div class="mode-page-heading"><div><span class="mode-kicker">ENVIRONMENT MONITOR</span><h1>環境總覽</h1></div><span class="data-mode-tag">${G.icon('chart-line')}感測數據</span></div>${G.state.plants.length?`<div class="data-kpis"><div><span>在線設備</span><strong>${online.length}<small> / ${plants.length}</small></strong></div><div class="${abnormal.length?'kpi-alert':''}"><span>異常植株</span><strong>${abnormal.length}<small> 株</small></strong></div><a href="${G.href('tasks.html')}"><span>待處理</span><strong>${pending.length}<small> 項 ${G.icon('caret-right')}</small></strong></a></div>${filters()}${focus?`<section class="data-observation"><div class="row between"><h2>趨勢觀測</h2>${G.nav('plant.html?id='+focus.id,'詳細 '+G.icon('arrow-up-right'),'text-link')}</div><label class="sr-only" for="overview-plant">觀測植物</label><select id="overview-plant">${plants.map(p=>`<option value="${p.id}" ${p.id===focus.id?'selected':''}>${G.esc(p.name)} · ${G.sensorState(p)}</option>`).join('')}</select><div class="overview-readings">${Object.keys(G.readings).map(k=>{const r=G.reading(focus,k);return `<div class="${r.abnormal?'reading-alert':''}"><span>${r.short}</span><strong>${r.display}<small>${r.unit}</small></strong><em>${r.status}</em></div>`}).join('')}</div><div class="chart-toolbar"><label class="sr-only" for="overview-metric">趨勢指標</label><select id="overview-metric">${Object.entries(G.readings).map(([k,r])=>`<option value="${k}" ${k===overviewMetric?'selected':''}>${r.label}</option>`).join('')}</select><span>過去 24 小時</span></div>${focus.online?'<div class="chart-wrap overview-chart"><canvas id="overview-chart" role="img" aria-label="所選植物的模擬指標趨勢"></canvas></div><p class="chart-source">模擬數據 · 色帶為該植物的理想範圍</p>':'<div class="data-offline">'+G.icon('wifi-slash')+'<p>設備離線，暫無可用讀值。<br>最後回報：'+G.esc(focus.lastSeen)+'</p></div>'}</section>`:'<div class="data-offline">這個花圃尚未加入設備。</div>'}<div class="section-head"><h2>全部感測讀值</h2><span class="small muted">${plants.length-online.length} 台離線</span></div><div class="sensor-list">${rows.map(G.sensorRow).join('')}</div>`:empty('simple')}`);
  bindFilters();
  document.getElementById('overview-plant')?.addEventListener('change',e=>{sensorFocus=e.target.value;G.refresh()});
  document.getElementById('overview-metric')?.addEventListener('change',e=>{overviewMetric=e.target.value;G.refresh()});
  if(focus?.online)G.makeChart(document.getElementById('overview-chart'),focus,overviewMetric,'24');
 };
})();
