(function(){
 let tab=GB.params.get('tab')==='register'?'register':'login';
 GB.pages.login=()=>{const G=GB,isNew=tab==='register';
 G.mount(`${G.header('','','<span class="demo-badge">DEMO</span>')}<div class="auth-avatar">${renderPlant('monstera','happy')}</div><div class="auth-intro center"><h1>${isNew?'你的綠色故事，從這裡開始':'歡迎回來，綠色夥伴。'}</h1><p>${isNew?'先認識你，再一起認識植物。':'植物們，正在等你回家。'}</p></div><div class="segmented"><button data-tab="login" class="${!isNew?'active':''}">登入</button><button data-tab="register" class="${isNew?'active':''}">註冊</button></div><form id="auth-form">${isNew?'<label for="nickname">怎麼稱呼你？</label><input id="nickname" name="nickname" placeholder="你的暱稱" value="Kevin" maxlength="24" autocomplete="nickname" required>':''}<label for="email">Email</label><input id="email" name="email" inputmode="email" autocomplete="email" placeholder="hello@greenbuddy.demo" value="kevin@example.com" required><label for="password">密碼</label><input type="password" name="password" id="password" autocomplete="${isNew?'new-password':'current-password'}" placeholder="輸入任意密碼即可體驗" value="greenbuddy" required><div class="row between mt8"><span class="small muted">展示帳號，不會送出密碼</span>${!isNew?'<button type="button" class="text-link" id="forgot">忘記密碼？</button>':''}</div><div class="form-error" role="status" id="auth-error"></div><button class="btn full" type="submit">${isNew?'建立我的帳號':'回到我的花圃'} ${G.icon('arrow-right')}</button></form><p class="footnote">此為互動展示版，任何非空白帳密皆可體驗。</p>`,false);
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;G.refresh()});
 const avatar=document.querySelector('.auth-avatar'),pass=document.getElementById('password');pass.onfocus=()=>avatar.classList.add('password-focus');pass.onblur=()=>avatar.classList.remove('password-focus');
 document.getElementById('forgot')?.addEventListener('click',()=>G.dialog({title:'重設信已寄出',text:'這是展示提示，沒有實際寄送電子郵件。請用任意帳密登入即可。',icon:'success'}));
 document.getElementById('auth-form').onsubmit=e=>{e.preventDefault();if(!document.getElementById('email').value.trim()||!pass.value.trim()){document.getElementById('auth-error').textContent='請填入帳號與密碼。';return}if(isNew){G.state=JSON.parse(JSON.stringify(MOCK));G.state.user.name=document.getElementById('nickname').value.trim()||'植物朋友';G.state.user.streak=0;G.state.user.daysTogether=0;G.state.user.xp=0;G.state.user.level=1;G.state.completedCount=0;G.state.plants=[];G.state.tasks=[];G.state.gardens=[{id:'g1',name:'我的小花圃',type:'室內',members:[G.state.user.name]}];G.save()}G.auth(true);if(isNew){G.go('style-pick.html');return}const dest=sessionStorage.getItem('greenbuddy.return');sessionStorage.removeItem('greenbuddy.return');G.go(dest||'home.html')};
 };
})();
