(function(){const G=GB;let phase='upload',photo='',species='monstera',query='';const candidates=[['monstera',92],['philodendron',5],['syngonium',3]];
 function identify(){phase='recognizing';G.refresh();const timer=setTimeout(()=>{phase=G.state.demo.lowConfidence?'search':'candidates';G.refresh()},2000);G.cleanup.push(()=>clearTimeout(timer))}
 G.pages['plant-new']=()=>{const d=G.state.draft;if(!d?.connected){G.mount(`${G.header('植物建檔','add-device.html')}<div class="empty-state"><h2>先讓感測器連上網路吧。</h2>${G.nav(d?'provision.html':'add-device.html','繼續設定','btn mt24')}</div>`,false);return}
 let content=`<div class="eyebrow caps">HELLO, LITTLE ONE</div><h1>認識你，<br>從第一片葉子開始。</h1><p class="muted small mt8">給它一張照片，我們一起找出它的名字。</p><div class="upload-box">${photo?`<img src="${G.esc(photo)}" alt="你上傳的植物照片">`:renderPlant(species,'happy')}${phase==='recognizing'?'<div class="scan-line"></div>':''}</div>`;
 if(phase==='upload')content+=`<input type="file" id="plant-photo" accept="image/*" capture="environment" hidden><button class="btn full" id="upload-photo">${G.icon('camera')} 拍照或上傳照片</button><div class="center mt8"><button class="text-link" id="sample-photo">使用示範植株</button></div><p class="footnote">照片只在目前頁面預覽，不會上傳。<br>辨識結果使用預設模擬資料。</p>`;
 if(phase==='recognizing')content+='<h2 class="center">正在認識它……</h2><p class="center small muted mt8">看看葉形，也看看它獨特的樣子。</p><div class="progress-track mt24"><i></i></div>';
 if(phase==='candidates')content+=`<h2>看起來，它可能是……</h2><p class="small muted mt8">選擇符合的品種，再幫它取個暱稱。</p>${candidates.map(([sp,confidence])=>`<button class="candidate" data-species="${sp}">${renderPlant(sp,'happy')}<span class="grow"><strong>${SPECIES[sp].name}</strong><span class="meter" style="display:block"><span style="width:${confidence}%"></span></span></span><em>${confidence}%</em></button>`).join('')}<div class="center"><button class="text-link" id="manual-species">都不對，手動搜尋品種</button></div>`;
 if(phase==='search')content+=`<h2>${G.state.demo.lowConfidence?'還不太確定，一起找找吧。':'找到它真正的名字。'}</h2><label for="species-search">搜尋品種</label><input id="species-search" value="${G.esc(query)}" placeholder="例如：龜背芋、虎尾蘭"><div id="species-results"></div>`;
 if(phase==='name')content+=`<span class="tag">${G.icon('check-circle')} ${SPECIES[species].name}</span><form id="plant-name-form"><label for="plant-nickname">你想叫它什麼？</label><div class="row"><input id="plant-nickname" maxlength="20" value="小綠" required placeholder="給它一個暱稱"><button type="button" id="random-name" class="icon-btn" aria-label="幫我取名">${G.icon('dice-five')}</button></div><p class="small muted mt8">${G.esc(G.garden(d.garden)?.name)} · ${G.esc(d.device)}</p><button class="btn full mt24" type="submit">歡迎來到我的生活 ${G.icon('heart')}</button></form><div class="center mt8"><button id="change-species" class="text-link">重新選擇品種</button></div>`;
 G.mount(`${G.header('植物建檔','provision.html','<span class="demo-badge">DEMO</span>')}${G.steps(3)}${content}`,false);
 document.getElementById('upload-photo')?.addEventListener('click',()=>document.getElementById('plant-photo').click());document.getElementById('sample-photo')?.addEventListener('click',identify);
 document.getElementById('plant-photo')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/'))return G.toast('請選擇圖片檔案。');if(photo)URL.revokeObjectURL(photo);photo=URL.createObjectURL(f);identify()});
 const bindSpecies=()=>document.querySelectorAll('[data-species]').forEach(b=>b.onclick=()=>{species=b.dataset.species;phase='name';G.refresh()});bindSpecies();
 document.getElementById('manual-species')?.addEventListener('click',()=>{phase='search';G.refresh()});document.getElementById('change-species')?.addEventListener('click',()=>{phase='search';G.refresh()});
 if(phase==='search'){const draw=()=>{const items=Object.entries(SPECIES).filter(([k,v])=>v.name.includes(query)||v.latin.toLowerCase().includes(query.toLowerCase()));document.getElementById('species-results').innerHTML=items.length?items.map(([sp,v])=>`<button class="candidate" data-species="${sp}">${renderPlant(sp,'happy')}<span>${G.esc(v.name)}</span></button>`).join(''):'<p class="muted small mt16">沒有符合的品種，試試其他關鍵字。</p>';bindSpecies()};document.getElementById('species-search').oninput=e=>{query=e.target.value;draw()};draw()}
 document.getElementById('random-name')?.addEventListener('click',()=>{const names=['波波','小福','阿綠','圓圓','芽芽','日和','小森','白白'];document.getElementById('plant-nickname').value=names[Math.floor(Math.random()*names.length)]});
 document.getElementById('plant-name-form')?.addEventListener('submit',e=>{e.preventDefault();if(G.state.plants.some(p=>p.device===d.device))return G.toast('這台設備已綁定。');const name=document.getElementById('plant-nickname').value.trim();if(!name)return G.toast('先幫它取個暱稱吧。');const sp=SPECIES[species],p={id:'p'+Date.now(),garden:d.garden,name,species,speciesName:sp.name,state:'happy',battery:100,online:true,lastSeen:'剛剛',accessory:null,device:d.device,days:1,ideal:JSON.parse(JSON.stringify(sp.ideal))};for(const k of ['soil','lux','temp','hum'])p[k]=Math.round((p.ideal[k][0]+p.ideal[k][1])/2);G.state.plants.push(p);G.state.draft=null;G.save();G.confetti();e.target.querySelector('button[type=submit]').disabled=true;setTimeout(()=>G.go('plant.html?id='+p.id),850)});
 };
})();
