(function(){
 let range='24',metric='soil';
 GB.pages.plant=()=>{
  const G=GB,p=G.plant(G.params.get('id'))||G.state.plants[0],mode=G.state.user.style;
  if(!p){G.mount(`${G.header('植物夥伴')}<div class="empty-state"><h2>這盆植物已經不在花圃裡了。</h2>${G.nav('home.html','回到首頁','btn mt24')}</div>`);return}
  const metricInfo={soil:['drop','土壤濕度','%',100],lux:['sun','光照','lux',Math.max(5000,p.lux||0,p.ideal.lux[1]*1.3)],temp:['thermometer','溫度','°C',45],hum:['cloud','空氣濕度','%',100]};
  const metrics=`<div class="metric-grid">${Object.entries(metricInfo).map(([key,[ico,label,unit,max]])=>{
   const r=G.reading(p,key),ideal=p.ideal[key];
   return `<div class="metric ${r.abnormal?'is-abnormal':''}"><label>${G.icon(ico)}${label}</label><div class="row between"><span class="metric-value">${r.display}<small>${unit}</small></span><span class="metric-status">${r.status}</span></div><div class="scale" aria-label="理想 ${ideal[0]} 到 ${ideal[1]} ${unit}"><span class="ideal" style="left:${ideal[0]/max*100}%;width:${(ideal[1]-ideal[0])/max*100}%"></span>${r.available?`<span class="pointer" style="left:calc(${Math.min(98,r.value/max*100)}% - 4px)"></span>`:''}</div>${mode==='simple'?`<p class="metric-ideal">理想 ${ideal[0]}–${ideal[1]} ${unit}</p>`:''}</div>`;
  }).join('')}</div>`;
  const advice=p.state==='thirsty'?'先摸摸表土，如果已乾燥，沿盆緣慢慢澆水。看到盆底有水流出後，倒掉托盤積水。':p.state==='hot'?'先把植物移到通風、沒有烈日直射的位置，等盆土降溫後再判斷是否需要澆水。':p.state==='offline'?'先檢查感測器電量，再確認 Wi-Fi 是否正常。離線時保留照護紀錄，請勿依過期數值判斷。':p.state==='overwater'?'暫停澆水，清空托盤積水並確認盆底排水孔暢通。等土壤逐漸變乾再恢復澆水。':p.state==='dark'?'移到明亮散射光的位置，逐步適應光線，避免突然放到強烈日照下。':p.state==='sleeping'?'讓植物安靜休息，等白天再確認盆土與葉片狀態。':G.abnormalReadings(p).length?'先確認感測器位置與環境，依照各指標的理想範圍調整照護。':'目前不用特別處理，看看葉片與盆土，維持原來的照護節奏就好。';
  const actions=`<div class="detail-care-actions"><button class="btn full" data-action="water" data-id="${p.id}">${G.icon('drop')} ${mode==='simple'?'記錄澆水':'我澆水了'}</button><div class="row mt8"><button class="btn outline small grow" id="measure">${G.icon('arrows-clockwise')} 立即量測</button>${G.nav('closet.html?plant='+p.id,G.icon('t-shirt')+' 換造型','btn outline small grow')}</div></div>`;
  const chart=`<section class="card chart-section mt24"><div class="row between mb16"><h2>${mode==='simple'?'歷史趨勢':mode==='game'?'環境紀錄':'它的小小日記'}</h2><select class="chart-select" id="chart-metric" aria-label="歷史指標">${Object.entries(metricInfo).map(([k,[i,n]])=>`<option value="${k}" ${k===metric?'selected':''}>${n}</option>`).join('')}</select></div><div class="segmented">${[['24','24 小時'],['7','7 天'],['30','30 天']].map(([v,n])=>`<button class="${range===v?'active':''}" data-range="${v}" aria-pressed="${range===v}">${n}</button>`).join('')}</div>${p.online?'<div class="chart-wrap"><canvas id="history-chart" role="img" aria-label="模擬歷史曲線"></canvas></div><div class="row between"><span class="legend">理想範圍</span><span class="small muted">模擬數據</span></div>':'<div class="data-offline">'+G.icon('wifi-slash')+'<p>感測器離線，暫無可用讀值。<br>恢復連線後可查看趨勢。</p></div>'}</section>`;
  const guidance=`<div class="section-head"><h2>${mode==='simple'?'照護建議':mode==='game'?'隊友照護指南':'把關心，變得剛剛好。'}</h2></div>${[['leaf','現在該做',advice],['calendar-blank','這週注意','每隔幾天觀察葉片、盆土與通風，光照改變時慢慢調整位置，避免頻繁搬動。'],['book-open','長期照護',SPECIES[p.species]?.desc||'定期觀察根系與生長速度，依季節調整澆水頻率。']].map(([i,t,copy],n)=>`<details ${n===0?'open':''}><summary>${G.icon(i)}${t}</summary><div class="details-body">${G.esc(copy)}</div></details>`).join('')}`;
  const device=`<details><summary>${G.icon('cpu')}設備資訊<span class="tag ${p.online?'':'gray'}">${p.online?'已連線':'離線'}</span></summary><div class="details-body"><div class="row between"><span>裝置編號</span><span>${G.esc(p.device)}</span></div><div class="row between"><span>電量</span><span>${p.battery}%</span></div><div class="row between"><span>訊號</span><span>${p.online?'良好 · −54 dBm':'無連線'}</span></div><div class="row between"><span>最後回報</span><span>${G.esc(p.lastSeen)}</span></div><div class="row between"><span>韌體版本</span><span>1.0.2-demo</span></div></div></details>`;
  const tasks=G.state.tasks.filter(t=>t.plant===p.id),pending=tasks.filter(t=>t.status==='pending');
  let content;
  if(mode==='game'){
   content=`<section class="quest-plant-header">${renderPlant(p.species,p.state,p.accessory)}<div><span class="mode-kicker">YOUR TEAMMATE</span><h1>${G.esc(p.name)}</h1><p>${G.esc(p.speciesName)} · ${G.esc(G.garden(p.garden)?.name)}</p><span class="tag">${pending.length} 項待辦</span></div></section>${G.questProgress(tasks)}<div class="section-head"><h2>隊友任務</h2><span class="small muted">完成可獲得 XP</span></div><div class="mission-list">${pending.length?pending.map(t=>G.taskCard(t,'game')).join(''):`<div class="quest-clear">${G.icon('check-circle')}<div><h3>目前沒有待辦</h3><p>這位隊友已經照顧好了。</p></div></div>`}</div>${G.rewardCard()}<details><summary>${G.icon('sliders-horizontal')}環境與照護工具</summary><div class="details-body">${metrics}${actions}</div></details>${chart}${guidance}${device}`;
  }else if(mode==='simple'){
   const abnormal=G.abnormalReadings(p);
   const alert=!p.online?`<div class="data-alert"><strong>設備離線</strong><p>最後回報：${G.esc(p.lastSeen)}。請先確認電源與網路。</p></div>`:abnormal.length?`<div class="data-alert"><strong>${abnormal.length} 項指標超出理想範圍</strong>${abnormal.map(r=>`<p>${r.label} ${r.display}${r.unit} ${r.status}，理想範圍 ${r.ideal[0]}–${r.ideal[1]}${r.unit}。</p>`).join('')}</div>`:`<div class="data-alert is-healthy">${G.icon('check-circle')} ${G.sensorState(p)}</div>`;
   content=`<section class="data-plant-header"><div class="row between"><h1>${G.esc(p.name)}</h1><span class="tag ${!p.online?'gray':abnormal.length?'warm':''}">${G.sensorState(p)}</span></div><p>${G.esc(p.speciesName)} · ${G.esc(G.garden(p.garden)?.name)}</p><div class="data-plant-meta"><span>${G.esc(p.device)}</span><span>電量 ${p.battery}%</span><span>${G.esc(p.lastSeen)}回報</span></div></section>${metrics}${chart}${alert}<div class="section-head"><h2>待處理事項</h2><span class="small muted">${pending.length} 項</span></div>${pending.map(t=>G.taskCard(t,'simple')).join('')||'<p class="small muted">目前沒有待處理事項。</p>'}${actions}${guidance}${device}`;
  }else{
   content=`<section class="detail-stage"><div class="speech">${G.esc(say(stateEvent(p.state),p))}</div>${renderPlant(p.species,p.state,p.accessory)}<span class="tag badge-float ${['thirsty','hot'].includes(p.state)?'warm':''}">${G.icon(STATE_META[p.state][1])}${STATE_META[p.state][0]}</span><div class="detail-name"><h1>${G.esc(p.name)}</h1><span>${G.esc(p.speciesName)}</span></div><p class="stage-label">${G.esc(G.garden(p.garden)?.name)} · 我們認識 ${p.days||G.state.user.daysTogether} 天了</p></section>${metrics}${actions}${chart}${guidance}${device}`;
  }
  G.mount(`${G.header(p.name,'home.html',G.nav('closet.html?plant='+p.id,G.icon('t-shirt'),'icon-btn','造型衣櫥'))}${G.modeTabs()}${content}`);
  document.getElementById('measure').onclick=()=>G.dialog({title:'已排入量測',text:'會在裝置下次醒來時量測，約 15 分鐘內。展示版不會連線到真實設備。',icon:'info'});
  document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{range=b.dataset.range;G.refresh()});
  document.getElementById('chart-metric').onchange=e=>{metric=e.target.value;G.refresh()};
  if(p.online)G.makeChart(document.getElementById('history-chart'),p,metric,range);
 };
})();
