(function(){const G=GB;let phase='intro',network='GreenHome_2.4G',lastRoute='';const iphone=/iPhone|iPad|iPod/.test(navigator.userAgent);
 const route=()=>G.state.demo.route==='auto'?(!iphone&&'bluetooth'in navigator?'ble':'ap'):G.state.demo.route;
 function waiting(){phase='waiting';G.refresh();const timer=setTimeout(()=>{phase=G.state.demo.outcome==='fail'?'fail':'success';if(phase==='success'){G.state.draft.connected=true;G.save();G.confetti()}G.refresh()},2800);G.cleanup.push(()=>clearTimeout(timer))}
 async function iosGuide(){const r=await G.dialog({title:'把陪伴，放到主畫面',html:'<div style="text-align:left"><p>1. 用 Safari 開啟 GreenBuddy。</p><p>2. 點底部「分享」按鈕。</p><p>3. 選擇「加入主畫面」。</p><p>4. 點「新增」，再從主畫面開啟。</p><p class="small muted mt16">此版展示安裝引導；系統推播與離線 PWA 功能尚未串接。</p></div>',confirmButtonText:'繼續建立植物檔案'});if(r.isConfirmed)G.go('plant-new.html')}
 G.pages.provision=()=>{const d=G.state.draft;if(!d){G.mount(`${G.header('連上網路','add-device.html')}<div class="empty-state"><h2>先找到你的裝置吧。</h2>${G.nav('add-device.html','開始綁定','btn mt24')}</div>`,false);return}const r=route();if(lastRoute&&lastRoute!==r)phase='intro';lastRoute=r;
 let body='';
 if(phase==='waiting'){body=`<div class="setup-result"><div class="loading-plant">${renderPlant('monstera','sleeping')}</div><h1>正在叫醒你的植物……</h1><p class="muted">讓它找找家的方向，再等一下下。</p><div class="progress-track mt24"><i></i></div><p class="footnote">小提醒：GreenBuddy 使用 2.4GHz Wi-Fi。</p></div>`}
 else if(phase==='success'){body=`<div class="setup-result celebrate"><div class="loading-plant">${renderPlant('monstera','happy','bow')}</div><span class="tag">${G.icon('check-circle')} 已連線</span><h1>嗨！我醒來了。</h1><p class="muted">${G.esc(d.device)} 已經找到家的方向。<br>接著，讓我們認識盆裡的夥伴。</p><button class="btn full mt24" id="profile-next">幫它建立檔案 ${G.icon('arrow-right')}</button>${!iphone?'<button class="text-link mt8" id="ios-guide">看看 iPhone 主畫面加入方式</button>':''}</div>`}
 else if(phase==='fail'){body=`<div class="setup-result"><div class="loading-plant">${renderPlant('monstera','offline')}</div><span class="tag warm">連線逾時</span><h1>還差一點點，<br>我們再試一次。</h1><ul class="muted"><li>確認 Wi-Fi 是 2.4GHz 頻段。</li><li>檢查密碼的大小寫與空格。</li><li>讓裝置靠近路由器，約 3 公尺內。</li></ul><button class="btn full mt24" id="retry">再試一次 ${G.icon('arrows-clockwise')}</button></div>`}
 else if(r==='ble'){body=`<div class="eyebrow caps">LET'S GET CONNECTED</div><h1>讓小夥伴，<br>連上家的訊號。</h1><div class="notice row">${G.icon('bluetooth')}<span>我們會用藍牙來設定 Wi-Fi。<br>此展示版會模擬裝置選擇。</span></div>${phase==='intro'?`<div class="loading-plant">${renderPlant('monstera','sleeping')}</div><button class="btn full" id="ble-connect">${G.icon('bluetooth')} 連接 GreenBuddy</button><p class="footnote">正式版請在瀏覽器視窗選 GreenBuddy-${G.esc(d.device.slice(-4))}。</p>`:`<span class="tag mt16">${G.icon('check-circle')} 已找到 GreenBuddy-${G.esc(d.device.slice(-4))}</span><h3 class="mt24">選擇你的 Wi-Fi</h3>${['GreenHome_2.4G','MyGarden_2.4G','LivingRoom'].map((n,i)=>`<button class="choice-row ${network===n?'selected':''}" data-network="${n}"><span class="choice-icon">${G.icon(i===2?'wifi-medium':'wifi-high')}</span><span class="grow">${n}</span>${G.icon(network===n?'check-circle':'lock-key')}</button>`).join('')}<form id="wifi-form"><label for="wifi-password">Wi-Fi 密碼</label><input type="password" id="wifi-password" autocomplete="off" placeholder="輸入任意示範密碼" required><button class="btn full mt24" type="submit">讓它連上網路 ${G.icon('arrow-right')}</button><p class="footnote">展示版不會保存或傳送你輸入的密碼。</p></form>`}`}
 else{body=`<div class="eyebrow caps">ONE STEP AT A TIME</div><h1>用熱點連線，<br>一樣很簡單。</h1><p class="muted small mt8">iPhone 或不支援藍牙的瀏覽器，跟著 4 步就好。</p>${[['hand-tap','按一下，喚醒裝置','長按裝置按鈕 3 秒，燈號開始呼吸。'],['qr-code','掃描連線 QR','用手機相機掃描裝置背面的連線 QR。'],['wifi-high','告訴它家的 Wi-Fi','在跳出的設定頁選擇 Wi-Fi、輸入密碼。'],['check-circle','回到這裡，等它上線','看到成功提示後，回來繼續。']].map(([i,t,s],n)=>`<div class="choice-row"><span class="choice-icon">${G.icon(i)}</span><div><h3>${n+1}. ${t}</h3><p>${s}</p></div></div>`).join('')}<button class="btn full mt24" id="ap-done">我完成了，等待裝置上線</button><p class="footnote">展示版不需要真的切換 Wi-Fi。</p>`}
 G.mount(`${G.header('連上網路','add-device.html','<span class="demo-badge">DEMO</span>')}${G.steps(2)}${body}`,false);
 document.getElementById('ble-connect')?.addEventListener('click',async()=>{const res=await G.dialog({title:'找到附近的小夥伴',text:`GreenBuddy-${d.device.slice(-4)} · 植物感測器`,confirmButtonText:'選擇並連線',showCancelButton:true});if(res.isConfirmed){phase='wifi';G.refresh()}});
 document.querySelectorAll('[data-network]').forEach(b=>b.onclick=()=>{network=b.dataset.network;G.refresh()});
 document.getElementById('wifi-form')?.addEventListener('submit',e=>{e.preventDefault();waiting()});document.getElementById('ap-done')?.addEventListener('click',waiting);
 document.getElementById('retry')?.addEventListener('click',()=>{phase='intro';G.refresh()});
 document.getElementById('profile-next')?.addEventListener('click',()=>iphone&&!G.state.settings.installed?iosGuide():G.go('plant-new.html'));document.getElementById('ios-guide')?.addEventListener('click',iosGuide);
 };
})();
