(function(){const G=GB;let mode=G.state.gardens.some(g=>g.envModule)?'auto':'quiz',step=0,answers=['客廳','北','新手','2～3 次','沒有'],chosen=false,petOnly=false;
 const questions=[['armchair','想把新夥伴放在哪裡？','先找一個你常常看得到它的角落。',['客廳','臥室','陽台','辦公室']],['sun-horizon','最近的窗戶，朝哪個方向？','光線，是我們幫你挑植物的重要線索。',['東','南','西','北','沒有窗']],['plant','你和植物，熟悉到哪一步？','不管是第一次，或第十盆，都有適合你的。',['新手','養過幾盆','很有經驗']],['calendar-blank','一週能留多少時間給它？','找到適合生活節奏的陪伴。',['1 次','2～3 次','幾乎每天']],['paw-print','家裡也有毛茸茸的室友嗎？','我們會把貓狗的安全一起放進考量。',['有','沒有']]];
 const env=()=>G.state.gardens.find(g=>g.envModule);
 const results=()=>{const pets=mode==='auto'?petOnly:answers[4]==='有',sunny=mode==='auto'||['南','西'].includes(answers[1]),beginner=answers[2]==='新手';const ids=pets?['peperomia','palm']:sunny?(beginner?['snake','succulent','monstera']:['monstera','succulent','pothos']):beginner?['pothos','snake','monstera']:['monstera','pothos','palm'];return ids.map((id,i)=>({id,score:96-i*4,reasons:[pets?'已篩選一般列為寵物友善的品種':sunny?'適合明亮角落，避開午間烈日':'適合有散射光的室內角落',SPECIES[id].difficulty===1?'照護門檻較低，新手也能慢慢上手':'適合願意定期觀察葉片的你',mode==='auto'?'依花圃 7 天模擬環境資料挑選':answers[1]==='沒有窗'?'無窗空間仍需要補充植物燈':`可以從${answers[0]}的一個小角落開始`]}))};
 G.pages.select=()=>{
 let html=`${G.header()}<div class="eyebrow caps">FIND YOUR GREEN MATCH</div><h1>找到，剛剛好的那一盆。</h1>`;
 if(mode==='quiz'){const [icon,title,sub,opts]=questions[step];html+=`<div class="question-progress">${questions.map((_,i)=>`<i class="${i<=step?'active':''}"></i>`).join('')}</div><div class="row between"><span class="small muted">QUESTION ${String(step+1).padStart(2,'0')} / 05</span>${step?'<button class="text-link" id="quiz-back">上一題</button>':''}</div><div class="question-illustration">${G.icon(icon)}</div><h2 class="center">${title}</h2><p class="center muted small mt8 mb16">${sub}</p>${opts.map((o,i)=>`<button class="choice-row ${chosen&&answers[step]===o?'selected':''}" data-answer="${G.esc(o)}"><span class="grow">${o}</span>${G.icon(chosen&&answers[step]===o?'check-circle':'circle')}</button>`).join('')}<button class="btn full mt24" id="quiz-next" ${chosen?'':'disabled'}>${step===4?'看看適合我的植物':'下一題'} ${G.icon('arrow-right')}</button>${env()?'<div class="center mt8"><button class="text-link" id="use-env">改用環境模組推薦</button></div>':''}`}
 else{const automatic=mode==='auto',garden=env();html+=`<p class="small muted mt8">${automatic?'讓家裡的光與空氣，幫你牽一條綠色的線。':'依照你的生活節奏，為你挑了這幾位夥伴。'}</p>${automatic&&garden?`<div class="card mt16"><div class="row">${G.icon('broadcast')}<h3>${G.esc(garden.name)} · 過去 7 天</h3><span class="tag gray">模擬</span></div><div class="env-row"><span>平均 18,000 lux</span><span>24–33°C</span><span>62% RH</span></div><label class="row" style="margin-bottom:0"><input type="checkbox" id="pet-filter" ${petOnly?'checked':''}>家有貓狗，只看友善植物</label></div>`:`<div class="chip-row mt16"><span class="tag">${G.esc(answers[0])}</span><span class="tag">${G.esc(answers[1])}${answers[1]==='沒有窗'?'':'向採光'}</span><span class="tag">${G.esc(answers[2])}</span>${answers[4]==='有'?'<span class="tag">寵物友善</span>':''}</div>`}<div class="section-head"><h2>這幾盆，和你很合拍。</h2><span class="small muted">左右滑動 ${G.icon('arrows-left-right')}</span></div><div class="swiper recommend-swiper"><div class="swiper-wrapper">${results().map(({id,score,reasons})=>{const s=SPECIES[id],wish=G.state.wishlist.includes(id);return `<div class="swiper-slide"><article class="recommendation"><div class="rec-stage">${renderPlant(id,'happy')}<div class="match-ring" title="示範適合度">${score}%</div></div><div class="row between"><div><h2>${s.name}</h2><span class="latin">${s.latin}</span></div><button class="icon-btn" data-wish="${id}" aria-label="${wish?'移出':'加入'}${s.name}願望清單" style="color:${wish?'#bd7966':'var(--sub)'}">${G.icon(wish?'heart-straight':'heart')}</button></div><ul class="reasons">${reasons.map(t=>`<li>${G.icon('check-circle')}${t}</li>`).join('')}</ul><div class="row between"><span class="small muted">照護難度 ${'✦'.repeat(s.difficulty)}${'·'.repeat(3-s.difficulty)}</span><span class="tag ${s.pet?'':'warm'}">${s.pet?'寵物友善':s.pet===null?'依品種確認':'避免寵物啃食'}</span></div><button class="btn secondary full mt16" data-rec-detail="${id}">了解它的小習慣 ${G.icon('arrow-up-right')}</button></article></div>`}).join('')}</div><div class="swiper-pagination"></div></div><div class="center"><button class="text-link" id="quiz-restart">${G.icon('arrows-clockwise')} ${automatic?'回答 5 題，認識你的生活':'重新測驗'}</button></div>${G.state.wishlist.length?`<div class="section-head"><h2>心裡先留一個位置</h2><span class="small muted">願望清單</span></div><div class="stack">${G.state.wishlist.map(id=>`<div class="task-mini">${renderPlant(id,'happy')}<div class="grow"><h3>${SPECIES[id].name}</h3><p>期待有一天，一起生活。</p></div><button class="icon-btn" data-wish="${id}" aria-label="移出${SPECIES[id].name}願望清單">${G.icon('x')}</button></div>`).join('')}</div>`:''}<p class="footnote">適合度與推薦為展示用規則，非實際環境評估。<br>即使是友善品種，仍應避免寵物啃食。</p>`}
 G.mount(html);
 document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{answers[step]=b.dataset.answer;chosen=true;G.refresh()});document.getElementById('quiz-next')?.addEventListener('click',()=>{if(step<4){step++;chosen=false}else mode='result';G.refresh();document.querySelector('.phone-scroll').scrollTop=0});document.getElementById('quiz-back')?.addEventListener('click',()=>{step--;chosen=true;G.refresh()});
 document.getElementById('quiz-restart')?.addEventListener('click',()=>{mode='quiz';step=0;chosen=false;G.refresh()});document.getElementById('use-env')?.addEventListener('click',()=>{mode='auto';G.refresh()});document.getElementById('pet-filter')?.addEventListener('change',e=>{petOnly=e.target.checked;G.refresh()});
 document.querySelectorAll('[data-wish]').forEach(b=>b.onclick=()=>{const id=b.dataset.wish,exists=G.state.wishlist.includes(id);G.state.wishlist=exists?G.state.wishlist.filter(v=>v!==id):[...G.state.wishlist,id];G.save();G.refresh();G.toast(exists?'已移出願望清單。':'已把它放進願望清單。')});
 document.querySelectorAll('[data-rec-detail]').forEach(b=>b.onclick=()=>{const s=SPECIES[b.dataset.recDetail];G.dialog({title:s.name,html:`<div style="width:150px;margin:auto">${renderPlant(b.dataset.recDetail,'happy')}</div><p>${G.esc(s.desc)}</p><p class="small muted mt16">常見問題：多久澆一次？<br>頻率依盆器、介質與環境改變，請先確認盆土狀態，避免照固定天數澆水。</p>`,confirmButtonText:'記住它的小習慣'})});
 if(mode!=='quiz')G.swiper('.recommend-swiper');
 };
})();
